config/routes.rb
Rails.application.routes.draw do

  resources :comments
  # デバイス認証
  get 'users/index'
  get 'users/show'
  get 'users/user_page'

  # オーバーライドしたコントローラを読み込む
  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions'
  }
  resources :users, :only => [:index, :show]
  resources :user_profiles

end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
  validates :name, presence: true

end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :set_user_profile, only: [:show, :edit, :update, :destroy]
  skip_before_action :profile_exit?, only: [:new, :create]  

  def index
    @user_profiles = UserProfile.all
    @comment = Comment.all
  end

  def show
    @comment = Comment.find(params[:id].to_i) if Comment.find_by(id: params[:id])
  end

  def new
    @user_profile = UserProfile.new
  end

  def edit
  end

  def create
    @user_profile = UserProfile.new(user_profile_params)
    @user_profile.user_id = current_user.id
    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to @user_profile, notice: 'User profile was successfully created.' }
        format.json { render :show, status: :created, location: @user_profile }
      else
        format.html { render :new }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to @user_profile, notice: 'User profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_profile }
      else
        format.html { render :edit }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user_profile.destroy
    respond_to do |format|
      format.html { redirect_to user_profiles_url, notice: 'User profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = UserProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_profile_params
      params.require(:user_profile).permit(:user_id, :name, :gender, :age, :language, :db, :fw, :tools, :server, :developer_experience, :operater_experience, :tester_experience, :basic_design_experience, :details_design_experience, :test_design_experience, :appeal_text, :qualification)
    end
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/user_profiles/_form.html.erb
<%= form_with(model: user_profile, local: true) do |form| %>
  <% if user_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

      <ul>
      <% user_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label t('profile.user') %>
    <%= form.text_field :name, id: :user_profile_name %>
  </div>

  <div class="field">
    <label>男</label><%= form.radio_button :gender, "男" %> 
    <label>女</label><%= form.radio_button :gender, "女" %> 
  </div>

  <div class="field">
    <%= form.label t('profile.age') %>
    <%= form.text_field :age, id: :user_profile_age %>
  </div>

  <div class="field">
    <%= form.label t('profile.language') %>
    <%= form.text_field :language, id: :user_profile_language %>
  </div>

  <div class="field">
    <%= form.label t('profile.db') %>
    <%= form.text_field :db, id: :user_profile_db %>
  </div>

  <div class="field">
    <%= form.label t('profile.fw') %>
    <%= form.text_field :fw, id: :user_profile_fw %>
  </div>

  <div class="field">
    <%= form.label t('profile.tools') %>
    <%= form.text_field :tools, id: :user_profile_tools %>
  </div>

  <div class="field">
    <%= form.label t('profile.server') %>
    <%= form.text_field :server, id: :user_profile_server %>
  </div>

  <div class="field">
    <%= form.label t('profile.developer_experience') %>
    <label>有</label><%= form.radio_button :developer_experience, "true" %>
    <label>無</label><%= form.radio_button :developer_experience, "false" %>
    <label>
  </div>
 
  <div class="field">
    <%= form.label t('profile.operater_experience') %>
    <label>有</label><%= form.radio_button :operater_experience, "true" %>
    <label>無</label><%= form.radio_button :operater_experience, "false" %>
  </div>

  <div class="field">
    <%= form.label t('profile.tester_experience') %>
    <label>有</label><%= form.radio_button :tester_experience, "true" %>
    <label>無</label><%= form.radio_button :tester_experience, "false" %>
  </div>

  <div class="field">
    <%= form.label t('profile.basic_design_experience') %>
    <label>有</label><%= form.radio_button :basic_design_experience, "true" %>
    <label>無</label><%= form.radio_button :basic_design_experience, "false" %>
  </div>

  <div class="field">
    <%= form.label t('profile.detail_design_experience') %>
    <label>有</label><%= form.radio_button :detail_design_experience, "true" %>
    <label>無</label><%= form.radio_button :detail_design_experience, "false" %>
  </div>

  <div class="field">
    <%= form.label t('profile.test_design_experience') %>
    <label>有</label><%= form.radio_button :test_design_experience, "true" %>
    <label>無</label><%= form.radio_button :test_design_experience, "false" %>
  </div>

  <div class="field">
    <%= form.label t('profile.appeal_text') %>
    <%= form.text_field :appeal_text, id: :user_profile_appeal_text %>
  </div>

  <div class="field">
    <%= form.label t('profile.qualification') %>
    <%= form.text_field :qualification, id: :user_profile_qualification %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_profiles/edit.html.erb
<h1>Editing User Profile</h1>

<%= render 'form', user_profile: @user_profile %>

<%= link_to 'Show', @user_profile %> |
<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Profiles</h1>
  <tbody>
    <% @user_profiles.each do |user_profile| %>
      <div class ="profile">
        <%= link_to "#{user_profile.name}", user_profile %><br>
        <% if @comment[user_profile.id - 1].present?  %>
          <%= image_tag @comment[user_profile.id - 1].image.variant(resize: "300x300") %>
        <% end %>
      </div>
    <% end %>
  </tbody>
</table>

<div class="logout">
  <%= link_to 'LOGOUT', destroy_user_session_path, method: :delete %>
</div>

app/views/user_profiles/new.html.erb
<h1>New User Profile</h1>

<%= render 'form', user_profile: @user_profile %>

<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @comment.image.variant(resize: "300x300") if @comment.present? %>

<p>
  <strong><%= t('profile.user')  %></strong>
  <%= @user_profile.name %>
</p>

<p>
  <strong><%= t('profile.gender')  %></strong>
  <%= @user_profile.gender %>
</p>

<p>
  <strong><%= t('profile.age')  %></strong>
  <%= @user_profile.age %>
</p>

<p>
  <strong><%= t('profile.language')  %></strong>
  <%= @user_profile.language %>
</p>

<p>
  <strong><%= t('profile.db')  %></strong>
  <%= @user_profile.db %>
</p>

<p>
  <strong><%= t('profile.fw')  %></strong>
  <%= @user_profile.fw %>
</p>

<p>
  <strong><%= t('profile.tools')  %></strong>
  <%= @user_profile.tools %>
</p>

<p>
  <strong><%= t('profile.server')  %></strong>
  <%= @user_profile.server %>
</p>

<p>
  <strong><%= t('profile.developer_experience')  %></strong>
  <%= @user_profile.developer_experience %>
</p>

<p>
  <strong><%= t('profile.developer_experience')  %></strong>
  <%= @user_profile.operater_experience %>
</p>

<p>
  <strong><%= t('profile.operater_experience') %></strong>
  <%= @user_profile.tester_experience %>
</p>

<p>
  <strong><%= t('profile.tester_experience')  %></strong>
  <%= @user_profile.basic_design_experience %>
</p>


<p>
  <strong><%= t('profile.basic_design_experience')  %></strong>
  <%= @user_profile.details_design_experience %>
</p>

<p>
  <strong><%= t('profile.detail_design_experience')  %></strong>
  <%= @user_profile.test_design_experience %>
</p>

<p>
  <strong><%= t('profile.appeal_text') %></strong>
  <%= @user_profile.appeal_text %>
</p>

<p>
  <strong><%= t('profile.qualification') %></strong>
  <%= @user_profile.qualification %>
</p>

<%= link_to 'Back', user_profiles_path %><br>

<% if current_user.id == params[:id].to_i %>
  <%= link_to 'プロフィール編集', edit_user_profile_path(params[:id]) %>
<% end %>

<% if current_user.id == params[:id].to_i && @comment_flug.present? %>
  <%= link_to 'プロフィール画像編集', edit_comment_path(params[:id]) %>
<% end %>

<% if current_user.id == params[:id].to_i && @comment_flug.blank? %>
  <%= link_to 'プロフィール画像作成', new_comment_path(params[:id]) %>  
<% end %>